# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [7]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [8]:
# Your code here
my_list=[12,27,2,1,1,3]
my_arr=np.array([12,27,2,1,1,3])

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [16]:
# Your code here
print(my_list*4)
print(my_arr*4)

#when printing the list, it repeats the same list 4 times instead of mulitplying the individual values by 4 like the array

[12, 27, 2, 1, 1, 3, 12, 27, 2, 1, 1, 3, 12, 27, 2, 1, 1, 3, 12, 27, 2, 1, 1, 3]
[ 48 108   8   4   4  12]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [17]:
# Your code here
print(my_list+my_list) #adds the 2 lists together, not the individual values
print(my_arr+my_arr) #adds the individual values
print(my_list+my_arr) #adds the individual values


[12, 27, 2, 1, 1, 3, 12, 27, 2, 1, 1, 3]
[24 54  4  2  2  6]
[24 54  4  2  2  6]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [18]:
# Your code here
#print((my_list)-(my_list)) you cant subtract lists
print(my_arr-my_arr) #subtracts the individual values
print(my_list-my_arr) #subtracts the individual values

[0 0 0 0 0 0]
[0 0 0 0 0 0]


5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [19]:
# Your code here
#print(my_list*my_list) cant multiply lists together 
print(my_arr*my_arr) #multiplies the individual values
print(my_list*my_arr) #multiplies the individual values

[144 729   4   1   1   9]
[144 729   4   1   1   9]


7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [20]:
# Your code here
#print(my_list/my_list) cant divide lists together
print(my_arr/my_arr) #divides the individual values
print(my_list/my_arr) #divides the individual values

[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]


8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [33]:
# Your code here
#Lists are treated kind of like words (dont know a better way to explain this) in
#the sense that when you perform operators on them, they are treated as a whole and not
#like individual numbers like an array does. 

## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [21]:
# Your code here
def sec_value(two_d_array): #inputs a 2D array and outputs every second value in each row
    sec=list(two_d_array[:,1])
    return sec
arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
result=sec_value(arr3)
print(result)

#The array indexing section of the website helped me figure out how to access certain elements of the 2D array.
#The array slicing was also very helpful,It taught me how to use ':' to select all rows

[2, 5, 8]


In 2-3 sentences, describe what section of the website helped you write your function. 

In [ ]:
# Your comment here
#you would have to use a for loop to extract the 2nd value of every row individually.
#you need the for loop to go through each row. for example: [row[1] for row in nest_list]

How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [26]:
# Your code here
#my function will input an array and spit out the index of the array when the values are
#greater than or equal to 10
def greater_than_ten(arr):
    g=np.where(arr >= 10)[0]
    if len(g)==0: #checks new array of g that is created that holds all of the indexes that
        #are greater than or equal to 10, if the array is empty, it will read this message:
        print("no values greater than or equal to 10 are in this array")
    return g
test_1=np.array([44,8,5,10,4,3,15,0,8,6,10,10,4,12,5,10])
test_2=np.array([1,2,3,4,5,6,7,8,7,6,5,9,2,4,5,1,0,0,8,1])
result=greater_than_ten(test_1)
print(result)

[ 0  3  6 10 11 13 15]


In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [30]:
# Your code here
#example 1:shows the indexes where the values are equal to 3
arr = np.array([3,6,1,7,8,2,3,3])
x = np.where(arr == 3)
print(x)

#example 2: indexes where values are even
arr = np.array([2,4,6,7,5,4,1,2,8,10])
x = np.where(arr%2 == 0)
print(x)

#example 3: indexes where values are odd
arr = np.array([3,4,5,6,7,8,3,1,9])
x = np.where(arr%2 == 1)
print(x)

(array([0, 6, 7], dtype=int64),)
(array([0, 1, 2, 5, 7, 8, 9], dtype=int64),)
(array([0, 2, 4, 6, 7, 8], dtype=int64),)


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

In [31]:
# Your comment here
#From "searching arrays" section, I used the np.where() method. In the examples under this section,
#they used np.where() to find values in an array that are equal to a number, that are divisible
#by 2 and that are odd. I used it in my code to print the indexes of certain values in an array. 

# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [3]:
# Your code here
import even_sum

<module 'even_sum' from 'C:\\Users\\sarah\\ulab\\ulab_sarah\\homework7\\even_sum.py'>


Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [4]:
# Your code here
list1=[1,3,6,7,10,88,2]
even_sum.sum_even_numbers(list1)

106

I have provided you a separate module called `example.py`. Import that module here.

In [5]:
# Your code here
import example

With the following variables, use my module to show which of the rocket's escape!

In [9]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [10]:
# Your code here
statuses=example.rocket_launch(rocket_velocities,mass_of_planet,radius_of_planet)
print("Rocket 1:", statuses[0])
print("Rocket 2:", statuses[1])
print("Rocket 3:", statuses[2])

Rocket 1: Rocket left the planet!
Rocket 2: Rocket is orbiting around the planet.
Rocket 3: Rocket crashes back into the planet!


In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

In [ ]:
# Your comments here
"""
This code has detailed comments for what each function does which includes the input and outputs for each function
It has detailed names for variables and the return statements are short
"""

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

In [ ]:
# Your comment here
"""
My code is inspired by a class I am currently taking where I am learning about stellar masses
and how the mass of a star can effect its life cycle. My code will take an input array of 
different masses (in solar masses) and put it through 3 functions that will 1. determine what
kind of star it is depending on its initial mass, 2. calculate its lifetime and 3. determine
what will happen to the star at the end of its life.
"""

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?

In [30]:
# Your comment here
"""
Something I wanted to achieve in this code was to get as much information as possible from 
just one variable. So figuring out 3 functions that will 
"""

Once your module is complete, import it here.

In [6]:
#Your code here
import stellar_mass as sm

Call each of your functions in the cell below. Make sure to show the outputs! 

In [7]:
# Your code here
star_masses=np.array([[0.01,0.5,1.0],[2.0,5.0,10.0],[15.0,20.0,25.0]])
sm.call_func(star_masses)

Mass:0.01 Solar Masses, Type of Star: Brown Dwarf, Lifetime: Brown Dwarfs aren't a star! Their lifetime is infinite! Gyr, Fate of Star: Star will remain as a White Dwarf
Mass:0.50 Solar Masses, Type of Star: Main Sequence, Lifetime: 4.00 Gyr Gyr, Fate of Star: Star will evolve into a White Dwarf
Mass:1.00 Solar Masses, Type of Star: Main Sequence, Lifetime: 1.00 Gyr Gyr, Fate of Star: Star will evolve into a White Dwarf
Mass:2.00 Solar Masses, Type of Star: Main Sequence, Lifetime: 0.25 Gyr Gyr, Fate of Star: Star will evolve into a White Dwarf
Mass:5.00 Solar Masses, Type of Star: Main Sequence, Lifetime: 0.04 Gyr Gyr, Fate of Star: Star will evolve into a White Dwarf
Mass:10.00 Solar Masses, Type of Star: Big Star, Lifetime: 0.01 Gyr Gyr, Fate of Star: Star will end as a Neutron Star
Mass:15.00 Solar Masses, Type of Star: Big Star, Lifetime: 0.00 Gyr Gyr, Fate of Star: Star will end as a Neutron Star
Mass:20.00 Solar Masses, Type of Star: Big Star, Lifetime: 0.00 Gyr Gyr, Fate of Sta

# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!